/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dddad2",
        "secondary-fixed-dim": "#cec5bb",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f7f3eb",
        "secondary": "#645d55",
        "secondary-fixed": "#ebe1d7",
        "primary-fixed-dim": "#c8c6c5",
        "inverse-surface": "#31302b",
        "on-secondary-fixed-variant": "#4c463f",
        "surface-container-high": "#ece8e0",
        "tertiary-fixed-dim": "#e6c35b",
        "primary-container": "#1c1b1b",
        "on-tertiary-fixed-variant": "#574400",
        "on-background": "#1c1c17",
        "surface-tint": "#5f5e5e",
        "surface-container-highest": "#e6e2da",
        "on-tertiary-container": "#4f3d00",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#474746",
        "tertiary-container": "#c9a843",
        "on-secondary-container": "#68615a",
        "error": "#ba1a1a",
        "surface": "#fdf9f1",
        "error-container": "#ffdad6",
        "secondary-container": "#e8ded4",
        "on-surface-variant": "#444748",
        "tertiary": "#745b00",
        "primary-fixed": "#e5e2e1",
        "primary": "#000000",
        "on-error-container": "#93000a",
        "outline": "#747878",
        "tertiary-fixed": "#ffe08a",
        "on-tertiary-fixed": "#241a00",
        "on-primary-fixed": "#1c1b1b",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c8c6c5",
        "surface-variant": "#e6e2da",
        "on-surface": "#1c1c17",
        "surface-container": "#f1ede5",
        "outline-variant": "#c4c7c7",
        "on-secondary-fixed": "#1f1b15",
        "inverse-on-surface": "#f4f0e8",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fdf9f1",
        "background": "#fdf9f1",
        "on-primary-container": "#858383"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "topbar-height": "72px",
        "container-padding": "32px",
        "inline-gap": "12px",
        "sidebar-width": "240px",
        "stack-gap": "24px",
        "card-padding": "24px",
        "grid-gutter": "20px"
      },
      fontFamily: {
        "headline-md-mobile": ["'Instrument Serif'", "serif"],
        "label-sm": ["'Manrope'", "sans-serif"],
        "title-lg": ["'Manrope'", "sans-serif"],
        "headline-md": ["'Instrument Serif'", "serif"],
        "body-lg": ["'Manrope'", "sans-serif"],
        "body-md": ["'Manrope'", "sans-serif"],
        "label-md": ["'Manrope'", "sans-serif"],
        "headline-sm": ["'Instrument Serif'", "serif"],
        "display-lg": ["'Instrument Serif'", "serif"],
        "display": ["'Instrument Serif'", "serif"],
        "serif": ["'Instrument Serif'", "serif"],
        "sans": ["'Manrope'", "sans-serif"],
        "body": ["'Manrope'", "sans-serif"]
      },
      fontSize: {
        "headline-md-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "1", "fontWeight": "500" }],
        "title-lg": ["18px", { "lineHeight": "1.5", "fontWeight": "600" }],
        "headline-md": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-sm": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
